on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
      - run: ./gradlew testExamples
      - uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          check_name: Examples (${{ matrix.os }})
          fail_on_failure: false
          report_paths: 'example/**/build/test-results/**/TEST-*.xml'
